CREATE TRIGGER [tDelIntegracaoECDelVtexRelProdutos] 
    ON [INTEGRACAO_ECOMMERCE_PRODUTOS]
    AFTER DELETE
AS
    DELETE FROM VTEX_RELACAO_PRODUTOS_SKUS
    WHERE PRODUTOID IN (SELECT PRODUTOID FROM deleted)
GO