CREATE VIEW [dbo].V_WC_PRODUCTS AS
	SELECT DISTINCT P.PRODUTOID sku,
		P.DESCRICAO name,
		TP.TIPOPROD categoryid, 
		TP.DESCRICAO category,
		LOWER(REPLACE(RTRIM(LTRIM(tp.descricao)), ' ', '-')) category_slug,
		CASE WHEN (P.PESO IS NULL) THEN 0
			 ELSE P.PESO 
			 END AS weight,
		CASE WHEN (P.ALTURA IS NULL) THEN 0
			 ELSE P.ALTURA
			 END AS height, 
		CASE WHEN (P.LARGURA IS NULL) THEN 0
			 ELSE P.LARGURA
			 END AS width, 
		CASE WHEN (P.COMPRIMENTO IS NULL) THEN 0
			 ELSE P.COMPRIMENTO
			 END AS length,
		'simple' type,
		1 manage_stock,
		P.PRECOVENDA regular_price,
		SUM(A.QUANTIDADE) stock_quantity,
		CASE WHEN (SUM(A.QUANTIDADE) > 0) THEN 'instock'
			ELSE 'outofstock'
			 END AS stock_status,
		'' description,
		'' short_description,
		(SELECT TOP 1 PATH FROM PRODUTOS_IMAGENS PIMG WHERE P.PRODUTOID = PIMG.PRODUTOID) AS PATH,
		P.PRODUTOID slug
	FROM PRODUTOS P
	INNER JOIN TIPOPRODUTO TP ON (P.TIPOPROD = TP.TIPOPROD) 
	INNER JOIN ALMOXLOJAITENS A ON (P.PRODUTOID = A.PRODUTOID AND A.ENTIDADEID_LOJA IN (?, ?))
	WHERE exists(select produtoid from REGISTROS_SINCRONIZAR where P.PRODUTOID = PRODUTOID)
    GROUP BY P.PRODUTOID, P.DESCRICAO, TP.TIPOPROD, TP.DESCRICAO,
	P.PESO, P.ALTURA, P.LARGURA, P.COMPRIMENTO, P.PRECOVENDA