CREATE VIEW [dbo].[V_NEO_PRODUTOS_ATUALIZAR] AS
	SELECT PU.CODIGOBARRAS AS PRODUCT_ID_API,
	PU.PRODUTOID AS EXTERNAL_ID, P.PRECOVENDA AS PRICE, QUANTIDADE AS STOCK, ISNULL(P.PRECO_PROMOCAO, 0) AS PRICE_PROMOTION
	FROM PRODUTO_UND PU,
	ALMOXLOJAITENS ALM,
	PRODUTOS P
	WHERE P.PRODUTOID = PU.PRODUTOID
	AND ALM.ALMOXID = ?
	AND ALM.ENTIDADEID_LOJA = ?
	AND P.PRODUTOID = ALM.PRODUTOID