CREATE VIEW [dbo].v_G2AutoMobileLogin AS
	SELECT US.CODIGO, US.NOME, US.SENHA3, US.FUNCIONARIO, ISNULL(EN.ATIVO, 'N') ATIVO,
	0 VENDAS, 4 NUM_PEDIDOS, 1 DEVOLUCOES, 
	1000 TICKET_MEDIO, 1500 VENDA_LIQUIDA, ISNULL(USL.ENTIDADEID_LOJA, -1) ENTIDADEID_LOJA
	FROM USUARIOS US LEFT JOIN USUARIOS_LOJA USL ON (USL.USUARIO = US.CODIGO)
	LEFT JOIN ENTIDADES EN on (EN.ENTIDADEID = US.FUNCIONARIO)