CREATE VIEW v_G2AutoMobilePrevendas AS
Select P.PREVENDAID, P.DATA, P.ENTIDADEID_FUNC,     
   F.DESCRICAO as NomeVendedor, P.ENTIDADEID_CLIENTE, C.Descricao as NomeCliente, (select count(ITEM) from PREVENDAITEM I
   where I.PREVENDAID = P.PREVENDAID and I.ENTIDADEID_LOJA = P.ENTIDADEID_LOJA) as QtdItens, 
	(select sum(I.QUANTIDADE*I.PRECOUNIT) from PREVENDAITEM I   where I.PREVENDAID = P.PREVENDAID and I.ENTIDADEID_LOJA = P.ENTIDADEID_LOJA) as TotalPreVenda,
	P.ENTIDADEID_LOJA
   from prevenda P  join V_Clientes C on C.ENTIDADEID = P.ENTIDADEID_CLIENTE  join V_FUNCIONARIOS F on F.ENTIDADEID = P.ENTIDADEID_FUNC where P.isAutoAtendimento = 'S'