CREATE VIEW [dbo].v_G2AutoMobileProdutos AS
	SELECT P.PRODUTOID, P.CODIGOCLIENTE, P.DESCRICAO, P.UNIDADE, almox.menorpreco precoAVista, almox.precovenda precoAPrazo, 
	ISNULL(PIMG.PATH, '') imageUrlPath, ISNULL(ALMOX.QUANTIDADE, 0) QUANTIDADE,
	BUSCA = ISNULL(P.descricao, ' ') + ' ' +
			ISNULL(CAST(P.PRODUTOID AS VARCHAR(20)), ' ') + ' ' +
			ISNULL(P.codigoCliente, ' ') 
	FROM PRODUTOS P LEFT JOIN PRODUTOS_IMAGENS PIMG ON (P.PRODUTOID = PIMG.PRODUTOID)
	LEFT JOIN ALMOXLOJAITENS ALMOX ON (P.PRODUTOID = ALMOX.PRODUTOID AND ALMOX.ALMOXID = ? AND ALMOX.ENTIDADEID_LOJA = ?)
	WHERE  P.PRODUTOID > 0
