CREATE TABLE [dbo].[CARGA](
	[CARGAID] [int] NOT NULL,
	[DATA] [datetime] NOT NULL,
	[DESCRICAO] [varchar](40) NULL,
	[STATUS] [varchar](1) NOT NULL,
	[ENTIDADEID_MOTORISTA] [int] NULL,
	[KM_INICIAL] [float] NULL,
	[KM_FINAL] [float] NULL,
	[VEICULOID] [int] NULL,
	[ENTIDADEID_LOJA] [int] NOT NULL,
	[OBS] [text] NULL,
	[ENTREGUE] [varchar](1) NULL,
	[ENTIDADEID_TRANSP] [int] NULL,
	[ROTAID] [varchar](10) NULL,
	[DATA_SAIDA] [datetime] NULL,
	[DATA_RETORNO] [datetime] NULL,
	[TOTAL_ENTREGA] [float] NULL,
	[PESO_MAX] [float] NULL,
	[TIPOSERVID] [int] NULL,
	[ENTIDADEID_ENTREGADOR1] [int] NULL,
	[ENTIDADEID_ENTREGADOR2] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[CARGAID] ASC,
	[ENTIDADEID_LOJA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[CARGA]  WITH CHECK ADD FOREIGN KEY([ENTIDADEID_LOJA], [VEICULOID])
REFERENCES [dbo].[VEICULOS] ([ENTIDADEID_LOJA], [VEICULOID])
GO

ALTER TABLE [dbo].[CARGA]  WITH CHECK ADD FOREIGN KEY([ENTIDADEID_TRANSP])
REFERENCES [dbo].[ENTIDADES] ([ENTIDADEID])
GO

ALTER TABLE [dbo].[CARGA]  WITH CHECK ADD  CONSTRAINT [FK_CARGA_TIPOSERV] FOREIGN KEY([TIPOSERVID])
REFERENCES [dbo].[TIPOSERVICO] ([TIPOSERVID])
GO

ALTER TABLE [dbo].[CARGA] CHECK CONSTRAINT [FK_CARGA_TIPOSERV]
GO

