CREATE TABLE [dbo].[CARGA_ROMANEIO_PED](
	[ROMANEIOID] [int] NOT NULL,
	[CARGAID] [int] NOT NULL,
	[ENTIDADEID_LOJA] [int] NOT NULL,
	[CONTA] [int] NOT NULL,
	[ORDEM] [varchar](2) NULL,
	[DATARECEBIMENTO] [datetime] NULL,
	[ENTREGUE] [varchar](100) NULL,
	[MOTIVONAOENTREGUE] [varchar](100) NULL,
	[VALOR_ENTREGA] [float] NULL,
	[SERVICO_COBRANCA] [varchar](255) NULL,
	[ENTIDADEID_CLIENTE_COBRANCA] [int] NULL,
	[PAGAR_NA_HORA] [varchar](1) NULL,
	[tituloid] [int] NULL,
	[SEPARADO] [varchar](1) NULL,
	[ENTIDADEID_LOJA_PEDIDO] [int] NULL,
	[LATITUDE] [varchar](20) NULL,
	[LONGITUDE] [varchar](20) NULL,
	[CIDADE] [varchar](40) NULL,
	[ESTADO] [varchar](20) NULL,
	[CEP] [varchar](20) NULL,
	[RUA] [varchar](100) NULL,
	[DATA_CHECKIN] [datetime] NULL,
	[DATA_ENTREGA] [datetime] NULL,
	[DATA_NAO_ENTREGUE] [datetime] NULL,
	[OCORRENCIAID] [int] NULL,
	[DATA_CHECKIN_UPD] [datetime] NULL,
	[DATA_ENTREGA_UPD] [datetime] NULL,
	[DATA_NAO_ENTREGUE_UPD] [datetime] NULL,
PRIMARY KEY NONCLUSTERED 
(
	[ROMANEIOID] ASC,
	[CARGAID] ASC,
	[ENTIDADEID_LOJA] ASC,
	[CONTA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CARGA_ROMANEIO_PED] ADD  DEFAULT ('N') FOR [SEPARADO]
GO

ALTER TABLE [dbo].[CARGA_ROMANEIO_PED]  WITH CHECK ADD FOREIGN KEY([CARGAID], [ENTIDADEID_LOJA], [ROMANEIOID])
REFERENCES [dbo].[CARGA_ROMANEIO] ([CARGAID], [ENTIDADEID_LOJA], [ROMANEIOID])
GO

ALTER TABLE [dbo].[CARGA_ROMANEIO_PED]  WITH CHECK ADD  CONSTRAINT [FK__CARGA_ROMANEIO_P__6CC31A31] FOREIGN KEY([CONTA], [ENTIDADEID_LOJA])
REFERENCES [dbo].[MOVIMENTO_DIA] ([CONTA], [ENTIDADEID_LOJA])
GO

ALTER TABLE [dbo].[CARGA_ROMANEIO_PED] CHECK CONSTRAINT [FK__CARGA_ROMANEIO_P__6CC31A31]
GO

ALTER TABLE [dbo].[CARGA_ROMANEIO_PED]  WITH CHECK ADD FOREIGN KEY([CARGAID], [ENTIDADEID_LOJA], [ROMANEIOID])
REFERENCES [dbo].[CARGA_ROMANEIO] ([CARGAID], [ENTIDADEID_LOJA], [ROMANEIOID])
GO


