CREATE TABLE [dbo].[CARGA_PEDIDOS](
	[CARGAID] [int] NOT NULL,
	[ENTIDADEID_LOJA] [int] NOT NULL,
	[CONTA] [int] NOT NULL,
	[DATASAIDA] [datetime] NULL,
	[ENTIDADEID_MOTORISTA] [int] NULL,
	[AVERBADO] [varchar](1) NULL,
	[VEICULOID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[CARGAID] ASC,
	[ENTIDADEID_LOJA] ASC,
	[CONTA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[CARGA_PEDIDOS]  WITH CHECK ADD FOREIGN KEY([CARGAID], [ENTIDADEID_LOJA])
REFERENCES [dbo].[CARGA] ([CARGAID], [ENTIDADEID_LOJA])
GO

