CREATE TABLE [dbo].[REGISTROS_SINCRONIZAR](
	[ENTIDADEID] [int] NULL,
	[CONTA] [int] NULL,
	[ENTIDADEID_LOJA] [int] NULL,
	[PRODUTOID] [int] NULL,
	[TITULOID] [int] NULL,
	[DATAENTRADA] [datetime] NULL,
	[DATASINCRONIZACAO] [datetime] NULL
) ON [PRIMARY]

GO

