CREATE TABLE [dbo].[CHECKLIST_OS](
	[CHECKID] [int] NOT NULL,
	[DESCRICAO] [varchar](60) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CHECKID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO