CREATE TABLE [dbo].[MOVIMENTO_DIA_CHECKLIST](
	[ENTIDADEID_LOJA] [int] NOT NULL,
	[CONTA] [int] NOT NULL,
	[CHECKID] [int] NOT NULL,
	[DESCRICAO] [varchar](60) NOT NULL,
	[RESPOSTA] [varchar](1) NOT NULL,
	[OBS] [varchar](200) NULL,
PRIMARY KEY CLUSTERED 
(
	[ENTIDADEID_LOJA] ASC,
	[CONTA] ASC,
	[CHECKID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[MOVIMENTO_DIA_CHECKLIST]  WITH CHECK ADD  CONSTRAINT [FK_MOVIMENTO_DIA_CHECKLIST_MOVIMENTO_DIA] FOREIGN KEY([CONTA], [ENTIDADEID_LOJA])
REFERENCES [dbo].[MOVIMENTO_DIA] ([CONTA], [ENTIDADEID_LOJA])
GO

ALTER TABLE [dbo].[MOVIMENTO_DIA_CHECKLIST] CHECK CONSTRAINT [FK_MOVIMENTO_DIA_CHECKLIST_MOVIMENTO_DIA]
GO


