CREATE TABLE [dbo].[PRODUTOS_IMAGENS](
	[ID] [int] NOT NULL,
	[PRODUTOID] [int] NOT NULL,
	[DESCRICAO] [varchar](60) NOT NULL,
	[PATH] [varchar](200) NULL,
	[IMG_BASE_64] [varchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC,
	[PRODUTOID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[PRODUTOS_IMAGENS]  WITH CHECK ADD  CONSTRAINT [FK_PRODUTOS_IMAGENS_PRODUTOID] FOREIGN KEY([PRODUTOID])
REFERENCES [dbo].[PRODUTOS] ([PRODUTOID])
GO

ALTER TABLE [dbo].[PRODUTOS_IMAGENS] CHECK CONSTRAINT [FK_PRODUTOS_IMAGENS_PRODUTOID]