CREATE TABLE [dbo].[TABLET_CONSIGNACAO_FATURAS](
	[FATURAID] [int] NOT NULL,
	[VALOR] [float] NOT NULL,
	[FORMAPAGID] [int] NULL,
	[RECEBIMENTO_ID] [int] NOT NULL,
	[CONSIGNACAO_ID] [varchar](30) NOT NULL,
	[DATA_PAGAMENTO] [datetime] NULL,
	[ENTIDADEID_VENDEDOR] [int] NULL,
	[ENTIDADEID_LOJA] [int] NULL,
	PRIMARY KEY (FATURAID, RECEBIMENTO_ID, CONSIGNACAO_ID))