CREATE TABLE [dbo].[TABLET_ENTIDADES_IMAGENS](
	[ID] [int] NOT NULL,
	[ENTIDADEID] [int] NOT NULL,
	[DESCRICAO] [varchar](60) NOT NULL,
	[PATH] [varchar](200) NULL,
	[IMG_BASE_64] [varchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC,
	[ENTIDADEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[TABLET_ENTIDADES_IMAGENS]  WITH CHECK ADD  CONSTRAINT [FK_ENTIDADES_IMAGENS_ENTIDADEID] FOREIGN KEY([ENTIDADEID])
REFERENCES [dbo].[ENTIDADES] ([ENTIDADEID])
GO

ALTER TABLE [dbo].[TABLET_ENTIDADES_IMAGENS] CHECK CONSTRAINT [FK_ENTIDADES_IMAGENS_ENTIDADEID]