CREATE TABLE TABLET_CONSIGNACAO_RECEBIMENTO(
	RECEBIMENTO_ID INTEGER,
	CONSIGNACAO_ID VARCHAR(20),
	PRODUTO_ID INTEGER,
	DATA_RECEBIMENTO DATETIME,
	DEVOLUCOES INTEGER,
	COMPRAS INTEGER,
	DOCUMENTO VARCHAR(20),
	ENTIDADEID_VENDEDOR INTEGER,
	PRIMARY KEY (RECEBIMENTO_ID, CONSIGNACAO_ID, PRODUTO_ID))