CREATE TABLE [dbo].[tablet_entidades](
	[tipo] [varchar](1) NULL,
	[codcli] [varchar](10) NULL,
	[descricao] [varchar](60) NULL,
	[descricao2] [varchar](40) NULL,
	[bairro] [varchar](20) NULL,
	[cidade] [varchar](20) NULL,
	[uf] [varchar](2) NULL,
	[entidadeid] [int] NOT NULL,
	[tipo_jf] [varchar](1) NULL,
	[tipoentidadeid] [int] NULL,
	[entidadeid_vendedor] [int] NULL,
	[tabprecoid] [varchar](10) NULL,
	[profid] [int] NULL,
	[carteiraid_old] [varchar](20) NULL,
	[regtributariaid] [int] NULL,
	[cidade_id] [int] NULL,
	[uf_id] [int] NULL,
	[regtribid_pis_cofins] [int] NULL,
	[paisid] [varchar](6) NULL,
	[isento_cgf] [varchar](1) NULL,
	[carteira_subid] [int] NULL,
	[atividadeid] [int] NULL,
	[pais] [varchar](6) NULL,
	[idg2] [int] NOT NULL,
	[cnpj_cpf] [varchar](20) NULL,
	[ativo] [varchar](1) NULL,
	[carteiraid] [int] NULL,
	[fone] [varchar](40) NULL,
	[inscricao] [varchar](20) NULL,
	[endereco] [varchar](40) NULL,
	[cep] [varchar](20) NULL,
	[complemento] [varchar](80) NULL,
	[cadastrado_tablet] [int] NULL,
	[numero] [varchar](20) NULL,
	[DATALEITURA] [DATETIME] NULL,
	OBS VARCHAR(400),
	REFERENCIA_COMPLEMENTO VARCHAR(300),
    RESPONSAVEL_CONTATO VARCHAR(300),
    EMAIL VARCHAR(100),
 CONSTRAINT [tablet_entidades_pkey] PRIMARY KEY CLUSTERED 
(
	[entidadeid] ASC,
	[idg2] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

