CREATE TABLE [dbo].[INTEGRACAO_ECOMMERCE_PRODUTOS](
	[INTEGRACAOID] [int] NOT NULL,
	[ENTIDADEID_LOJA] [int] NOT NULL,
	[ITEM] [int] NOT NULL,
	[PRODUTOID] [int] NOT NULL,
	[ALMOXID] [int] NOT NULL,
	[PRECO_VENDA] [float] NOT NULL,
	[PRECO_PROMOCAO] [float] NULL,
	[PROMOCAO_INICIO] [datetime] NULL,
	[PROMOCAO_FIM] [datetime] NULL,
	[PRODUTOID_API] [varchar](30) NULL,
	[SH_DATA_INSERCAO] [datetime] NULL,
	[PERC_DESCONTO_PROMOCAO] [float] NULL,
PRIMARY KEY NONCLUSTERED 
(
	[INTEGRACAOID] ASC,
	[ENTIDADEID_LOJA] ASC,
	[ITEM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

