CREATE VIEW [dbo].[V_MG_PRODUCT_IMAGE] AS
	SELECT PRODUTOID SKU, 
		   CASE WHEN PATH LIKE '%.jpg%' THEN 'image/jpeg' ELSE 'image/' + RIGHT(PATH, 3) END AS IMG_TYPE, 
		   CASE WHEN PATH LIKE '%.jpg%' THEN CAST(PRODUTOID AS VARCHAR(20)) + '.jpeg' ELSE CAST(PRODUTOID AS VARCHAR(20)) + RIGHT(PATH, 4) END AS IMG_NAME, 
		   IMG_BASE_64 FROM PRODUTOS_IMAGENS 
	WHERE PRODUTOID IN (SELECT SKU FROM V_MG_PRODUCTS)