CREATE TABLE [dbo].[ALMOXLOJAITENS](
	[ALMOXID] [int] NOT NULL,
	[ENTIDADEID_LOJA] [int] NOT NULL,
	[PRODUTOID] [int] NOT NULL,
	[LOCAL] [varchar](20) NULL,
	[QUANTIDADE] [float] NULL,
	[PRECOMEDIO] [float] NULL,
	[PRECOCOMPRA] [float] NULL,
	[ULTIMOPRECO] [float] NULL,
	[PRECOVENDA] [float] NULL,
	[MENORPRECO] [float] NULL,
	[QTMINIMA] [float] NULL,
	[QTDULTIMACOMPRA] [float] NULL,
	[DATAULTIMACOMPRA] [datetime] NULL,
	[DATAULTIMAVENDA] [datetime] NULL,
	[PRECO_PROMOCAO] [float] NULL,
	[PRECO_PROMOCAO_de] [datetime] NULL,
	[PRECO_PROMOCAO_ate] [datetime] NULL,
	[USUARIO] [varchar](20) NULL,
	[DATAZERO] [datetime] NULL,
	[FORNECEDOR_ULTIMACOMP] [int] NULL,
	[FAIXAID] [int] NULL,
	[ULTIMOPRECOVENDA] [float] NULL,
	[DT_ATUALIZACAO] [datetime] NULL,
	[UC_NUMNOTA] [varchar](10) NULL,
	[UC_DATAEMISSAO] [datetime] NULL,
	[PONTO_RESSUPRIMENTO] [float] NULL,
	[desconto] [float] NULL,
	[obs] [varchar](255) NULL,
	[data_alteracao_preco] [datetime] NULL,
	[USUARIO_PRECO] [varchar](50) NULL,
	[PRECO_ALT_OLD] [float] NULL,
	[PRECO_ALT_NEW] [float] NULL,
	[DISPONIVEL] [varchar](1) NULL,
 CONSTRAINT [PK__ALMOXLOJAITENS__5629CD9C] PRIMARY KEY NONCLUSTERED 
(
	[ALMOXID] ASC,
	[ENTIDADEID_LOJA] ASC,
	[PRODUTOID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[ALMOXLOJAITENS]  WITH NOCHECK ADD  CONSTRAINT [FK__ALMOXLOJA__PRODU__7E37BEF6] FOREIGN KEY([PRODUTOID])
REFERENCES [dbo].[PRODUTOS] ([PRODUTOID])
GO

ALTER TABLE [dbo].[ALMOXLOJAITENS] CHECK CONSTRAINT [FK__ALMOXLOJA__PRODU__7E37BEF6]
GO

ALTER TABLE [dbo].[ALMOXLOJAITENS]  WITH NOCHECK ADD  CONSTRAINT [FK__ALMOXLOJAITENS__7F2BE32F] FOREIGN KEY([ENTIDADEID_LOJA], [ALMOXID])
REFERENCES [dbo].[ALMOXLOJA] ([ENTIDADEID_LOJA], [ALMOXID])
GO

ALTER TABLE [dbo].[ALMOXLOJAITENS] CHECK CONSTRAINT [FK__ALMOXLOJAITENS__7F2BE32F]
GO

