CREATE TABLE [dbo].[ENTREGA](
	[ENTIDADEID_LOJA] [int] NOT NULL,
	[ENTREGAID] [int] NOT NULL,
	[DATAEMISSAO] [datetime] NULL,
	[DATAFINALIZACAO] [datetime] NULL,
	[STATUS] [varchar](1) NULL,
	[OBS] [text] NULL,
	[USUARIO] [varchar](20) NULL,
	[USUARIO_FIM] [varchar](20) NULL,
	[ENTIDADEID_MOTORISTA] [int] NULL,
	[VEICULOID] [int] NULL,
	[LOCAL_ENTREGA] [varchar](80) NULL,
	[TIPO_ENTREGA] [varchar](1) NULL,
	[OBS_FECHAMENTO] [text] NULL,
	[ENTIDADEID_LOCAL_COLETA] [int] NULL,
	[PREVISAOENTREGA] [datetime] NULL,
	[NUMDOCUMENTO] [int] NULL,
	[TIPOSERVID] [int] NULL,
	[OBS2] [varchar](500) NULL,
	[OBSENTREGA] [varchar](1000) NULL,
PRIMARY KEY CLUSTERED 
(
	[ENTIDADEID_LOJA] ASC,
	[ENTREGAID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

