CREATE TABLE [dbo].[ENTREGA_MOVIMENTO](
	[ENTREGAID] [int] NOT NULL,
	[ENTIDADEID_LOJA] [int] NOT NULL,
	[CONTA] [int] NOT NULL,
	[ENTIDADEID_LOJA_MOVIMENTO] [int] NULL
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[ENTREGA_MOVIMENTO]  WITH CHECK ADD FOREIGN KEY([ENTIDADEID_LOJA], [ENTREGAID])
REFERENCES [dbo].[ENTREGA] ([ENTIDADEID_LOJA], [ENTREGAID])
GO

