CREATE TABLE [dbo].[ENTIDADES](
	[TIPO] [varchar](1) NOT NULL,
	[CODCLI] [varchar](10) NOT NULL,
	[DESCRICAO] [varchar](120) NULL,
	[DESCRICAO2] [varchar](120) NULL,
	[CNPJ_CPF] [varchar](20) NOT NULL,
	[INSCRICAO_ID] [varchar](20) NULL,
	[ENDERECO] [varchar](60) NULL,
	[BAIRRO] [varchar](40) NULL,
	[CEP] [varchar](10) NULL,
	[CIDADE] [varchar](60) NULL,
	[UF] [varchar](5) NULL,
	[OBS] [text] NULL,
	[FONE1] [varchar](15) NULL,
	[ENTIDADEID] [int] NOT NULL,
	[FONE2] [varchar](13) NULL,
	[FONE3] [varchar](13) NULL,
	[CONTATO] [varchar](20) NULL,
	[EMAIL] [varchar](200) NULL,
	[SITE] [varchar](40) NULL,
	[ATIVO] [varchar](1) NOT NULL,
	[CREDITO] [varchar](1) NOT NULL,
	[DESCONTO] [float] NULL,
	[TIPO_JF] [varchar](1) NOT NULL,
	[DATACADASTRO] [datetime] NOT NULL,
	[TIPOENTIDADEID] [int] NULL,
	[DATANAS] [datetime] NULL,
	[ENTIDADEID_VENDEDOR] [int] NULL,
	[ENTIDADEID_LOJA] [int] NULL,
	[LIMITECREDITO] [float] NULL,
	[RESPONSAVEL] [varchar](40) NULL,
	[RESPID] [varchar](20) NULL,
	[NUMDIA] [int] NULL,
	[TABPRECOID] [varchar](10) NULL,
	[PROFID] [int] NULL,
	[ANIVERSARIO] [varchar](5) NULL,
	[REGTRIBUTARIAID] [int] NULL,
	[TABPRECOID2] [varchar](10) NULL,
	[CARTEIRAID] [varchar](20) NULL,
	[INSCRICAO_MUN] [varchar](20) NULL,
	[cidade_id] [int] NULL,
	[uf_id] [int] NULL,
	[pais] [varchar](6) NULL,
	[protesta] [varchar](1) NULL,
	[PAISID] [varchar](6) NULL,
	[NUMERO] [varchar](10) NULL,
	[COMPLEMENTO] [varchar](120) NULL,
	[REGTRIB_PIS_COFINS] [int] NULL,
	[CONTACORRENTE] [varchar](1) NULL,
	[REGTRIBID_PIS_COFINS] [int] NULL,
	[OBSNOTA] [varchar](60) NULL,
	[ISENTO_CGF] [varchar](1) NULL,
	[CNAE] [varchar](20) NULL,
	[REGIME_TRIBUTARIO] [varchar](1) NULL,
	[INSCRICAO_ST] [varchar](20) NULL,
	[SUFRAMA] [varchar](20) NULL,
	[CH_DEVOLVIDO] [varchar](1) NULL,
	[CARTEIRA_SUBID] [int] NULL,
	[ATIVIDADEID] [int] NULL,
	[REGIME_NFSE] [int] NULL,
	[INCENTIVO_CULTURAL] [varchar](1) NULL,
	[VEND_NOME] [varchar](40) NULL,
	[CPF_INVALIDO] [varchar](1) NULL,
	[RETERISS] [varchar](1) NULL,
	[ALIQISS] [float] NULL,
	[OBSFAT] [text] NULL,
	[PATH_LOGO] [varchar](200) NULL,
	[LIMITECREDITO_MES] [float] NULL,
	[PONTOREFERENCIA] [varchar](40) NULL,
	[descontoboleto] [float] NULL,
	[DATA_ADMISSAO] [datetime] NULL,
	[DATA_DEMISSAO] [datetime] NULL,
	[AMBIENTE_NFCE] [varchar](1) NULL,
	[CERTIFICADO_NFCE] [varchar](500) NULL,
	[id_token_nfce] [varchar](6) NULL,
	[token_nfce] [varchar](50) NULL,
	[almoxid] [int] NULL,
	[indice_aproveitamento] [float] NULL,
	[foto] [image] NULL,
	[CERTIFICADO_NFSE] [varchar](500) NULL,
	[AMBIENTE_NFSE] [varchar](1) NULL,
	[CATEGORIAID] [int] NULL,
	[FUNDOCAIXA] [float] NULL,
	[OBS_ALIQ1] [varchar](500) NULL,
	[OBS_ALIQ2] [varchar](500) NULL,
	[EMAIL_FINANCEIRO] [varchar](100) NULL,
	[NFE_WS] [int] NULL,
	[NFE_AMBIENTE] [int] NULL,
	[COMO_CONHECEU] [varchar](40) NULL,
	[CANAL_PRIMEIRO_CONTATO] [varchar](40) NULL,
	[MODALIDADEID] [int] NULL,
	[verbamarketing] [float] NULL,
	[FONESMS] [varchar](15) NULL,
	[SPC_CodigoAssociado] [varchar](10) NULL,
	[SPC_CodigoOperador] [varchar](10) NULL,
	[SPC_SnhWebService] [varchar](10) NULL,
	[SPC_Homologacao] [bit] NULL,
	[TIPOFOLHAID] [int] NULL,
	[SIGEP_CONTRATOID] [varchar](10) NULL,
	[SIGEP_CARTAOID] [varchar](10) NULL,
	[SIGEP_USUARIO] [varchar](10) NULL,
	[SIGEP_SENHA] [varchar](10) NULL,
	[SIGEP_HOMOLOGACAO] [bit] NULL,
	[eExtrato_ChvAcesso] [varchar](50) NULL,
	[eExtrato_ChvSecreta] [varchar](50) NULL,
PRIMARY KEY NONCLUSTERED 
(
	[ENTIDADEID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[ENTIDADES]  WITH CHECK ADD FOREIGN KEY([CATEGORIAID])
REFERENCES [dbo].[ENTIDADES_CATEGORIA] ([CATEGORIAID])
GO

ALTER TABLE [dbo].[ENTIDADES]  WITH CHECK ADD FOREIGN KEY([TIPOENTIDADEID])
REFERENCES [dbo].[TIPOENTIDADE] ([TIPOENTIDADEID])
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT ((0)) FOR [LIMITECREDITO_MES]
GO

