CREATE TABLE [dbo].[PRODUTOS](
	[CODIGOCLIENTE] [varchar](50) NULL,
	[DESCRICAO] [varchar](130) NOT NULL,
	[UNIDADE] [varchar](7) NOT NULL,
	[PRECOVENDA] [float] NOT NULL,
	[PRECOCOMPRA] [float] NOT NULL,
	[ULTIMOPRECO] [float] NOT NULL,
	[PRECOMEDIO] [float] NOT NULL,
	[MENORPRECO] [float] NOT NULL,
	[IPI] [float] NOT NULL,
	[ICMS] [float] NOT NULL,
	[PRODUTOID] [int] NOT NULL,
	[TIPOPROD] [int] NULL,
	[DATACADASTRO] [datetime] NULL,
	[ULTIMACOMPRA] [datetime] NULL,
	[ENTIDADEID_FORNECEDOR] [int] NULL,
	[UND2] [varchar](7) NULL,
	[FATORUND2] [float] NULL,
	[ASSUNTO] [varchar](40) NULL,
	[EDICAO] [varchar](20) NULL,
	[NOMEAUTOR] [varchar](40) NULL,
	[PESO] [float] NULL,
	[COMPRIMENTO] [float] NULL,
	[ALTURA] [float] NULL,
	[LARGURA] [float] NULL,
	[ISBN] [varchar](20) NULL,
	[ANO] [int] NULL,
	[ATIVO] [varchar](1) NULL,
	[CST1] [varchar](3) NULL,
	[CST2] [varchar](3) NULL,
	[COMPOSICAO] [varchar](40) NULL,
	[CARACTERISTICA] [text] NULL,
	[GARANTIA] [int] NULL,
	[LOTE] [varchar](1) NULL,
	[CODFORN] [varchar](20) NULL,
	[CLAFISCAL] [varchar](20) NULL,
	[SITTRIBUTARIAID] [varchar](6) NULL,
	[comissao] [float] NULL,
	[Foto] [image] NULL,
	[VAR_PV_ACIMA] [float] NULL,
	[VAR_PV_ABAIXO] [float] NULL,
	[IMPOSTOID_PISCOFINS] [int] NULL,
	[CST1_COFINS] [varchar](2) NULL,
	[CST1_PIS] [varchar](2) NULL,
	[MODALIDADE_BC] [int] NULL,
	[INDICE1] [float] NULL,
	[INDICE2] [float] NULL,
	[PRECOCONSUMIDOR] [float] NULL,
	[TIPOTITULOID] [int] NULL,
	[CLASSE] [int] NULL,
	[MARCAID] [int] NULL,
	[SAFRAID] [int] NULL,
	[ORIGEMID] [int] NULL,
	[GRUPOID] [int] NULL,
	[TIPOPRODID_FILHO] [int] NULL,
	[CODIGO_EAN] [varchar](20) NULL,
	[DESCRICAO_ECF] [varchar](120) NULL,
	[IMPOSTOIPI_ID] [int] NULL,
	[CST1_IPI] [varchar](2) NULL,
	[CNPJ_PRODUTOR] [varchar](20) NULL,
	[APLICACAO1] [varchar](50) NULL,
	[APLICACAO2] [varchar](50) NULL,
	[CODFORN2] [varchar](10) NULL,
	[CODFORN3] [varchar](10) NULL,
	[ICMS_UND] [float] NULL,
	[GENID] [int] NULL,
	[CARACTERISCA2] [text] NULL,
	[CARACTERISTICA2] [text] NULL,
	[MARKUP] [float] NULL,
	[CODIGOFORN] [varchar](20) NULL,
	[MEDIDAS] [varchar](20) NULL,
	[TIPOPROD_NETO] [int] NULL,
	[TIPOITEMID] [varchar](2) NULL,
	[ESPECIEID] [int] NULL,
	[TIPOVEICULOID] [varchar](2) NULL,
	[COR_DEN_ID] [varchar](2) NULL,
	[TIPOCOMBUSTIVELID] [varchar](2) NULL,
	[COR_MONTADOR] [varchar](4) NULL,
	[COR_DESCRICAO] [varchar](40) NULL,
	[TIPOPINTURA] [varchar](1) NULL,
	[CILINDRADAS] [varchar](4) NULL,
	[POTENCIA] [varchar](4) NULL,
	[DIST_EIXOS] [float] NULL,
	[TRACAO] [float] NULL,
	[LOTACAO] [int] NULL,
	[COD_MARCA_MODELO] [int] NULL,
	[PESO_LIQUIDO] [float] NULL,
	[VEICULO] [varchar](1) NULL,
	[USAVALIDADE] [varchar](1) NULL,
	[DISPID_FORNECEDOR] [int] NULL,
	[GRUPOID2] [int] NULL,
	[USUARIO_CAD] [varchar](10) NULL,
	[USUARIO_EDIT] [varchar](10) NULL,
	[DATA_EDIT] [datetime] NULL,
	[CODNATUREZARECEITA] [varchar](5) NULL,
	[STATUSID] [int] NULL,
	[preco_promocao] [float] NULL,
	[PRECO_PROMOCAO_de] [datetime] NULL,
	[PRECO_PROMOCAO_ate] [datetime] NULL,
	[PRECO_FORNECEDOR] [float] NULL,
	[NPONTOS] [float] NULL,
	[CATEGORIAID] [int] NULL,
	[COLECAOID] [int] NULL,
	[FORNECEDOR_REF] [varchar](200) NULL,
	[APLICACAO3] [varchar](60) NULL,
	[APLICACAO4] [varchar](60) NULL,
	[APLICACAO5] [varchar](60) NULL,
	[markupmenorpreco] [float] NULL,
	[REFERENCIAID] [varchar](20) NULL,
	[RANK_VENDAS] [int] NULL,
	[ABC_VENDAS] [varchar](1) NULL,
	[cest] [varchar](7) NULL,
	[preco_sugerido] [float] NULL,
	[FRACIONADO] [varchar](1) NULL,
	[PRODUTO_SITE] [varchar](200) NULL,
	[PRECOVENDA_SUGESTAO] [float] NULL,
	[CODANVISA] [varchar](13) NULL,
	[CUSTOMIZADO] [varchar](1) NULL,
	[PRECOCOMPRA_NEGOCIADO] [float] NULL,
 CONSTRAINT [PK__PRODUTOS__70DDC3D8] PRIMARY KEY CLUSTERED 
(
	[PRODUTOID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[PRODUTOS]  WITH NOCHECK ADD  CONSTRAINT [FK__PRODUTOS__TIPOPR__31B762FC] FOREIGN KEY([TIPOPROD])
REFERENCES [dbo].[TIPOPRODUTO] ([TIPOPROD])
GO

ALTER TABLE [dbo].[PRODUTOS] CHECK CONSTRAINT [FK__PRODUTOS__TIPOPR__31B762FC]
GO

ALTER TABLE [dbo].[PRODUTOS]  WITH CHECK ADD FOREIGN KEY([TIPOPROD])
REFERENCES [dbo].[TIPOPRODUTO] ([TIPOPROD])
GO

ALTER TABLE [dbo].[PRODUTOS]  WITH CHECK ADD  CONSTRAINT [FK_PRD_PCT] FOREIGN KEY([CATEGORIAID])
REFERENCES [dbo].[PRODUTOS_CATEGORIA] ([CATEGORIAID])
GO

ALTER TABLE [dbo].[PRODUTOS] CHECK CONSTRAINT [FK_PRD_PCT]
GO

ALTER TABLE [dbo].[PRODUTOS]  WITH CHECK ADD  CONSTRAINT [FK_PRODUTOS_PRODUTO_IPI_RFB] FOREIGN KEY([IMPOSTOIPI_ID])
REFERENCES [dbo].[PRODUTO_IPI_RFB] ([IMPOSTOIPI_ID])
GO

ALTER TABLE [dbo].[PRODUTOS] CHECK CONSTRAINT [FK_PRODUTOS_PRODUTO_IPI_RFB]
GO

ALTER TABLE [dbo].[PRODUTOS]  WITH CHECK ADD  CONSTRAINT [FK_STATUS_PROD] FOREIGN KEY([STATUSID])
REFERENCES [dbo].[PRODUTO_STATUS] ([STATUSID])
GO

ALTER TABLE [dbo].[PRODUTOS] CHECK CONSTRAINT [FK_STATUS_PROD]
GO

