CREATE TABLE [dbo].[REGISTROS_SINCRONIZAR_SH](
	[PEDIDOID_API] [varchar](60) NOT NULL,
	[DATASINCRONIZACAO] [datetime] NULL,
 CONSTRAINT [PK_REGISTROS_SINCRONIZAR_SH] PRIMARY KEY CLUSTERED 
(
	[PEDIDOID_API] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[REGISTROS_SINCRONIZAR_SH]  WITH CHECK ADD FOREIGN KEY([PEDIDOID_API])
REFERENCES [dbo].[SH_PEDIDO] ([CODE])
GO

