CREATE TABLE [dbo].[SH_PAYMENT](
	[VALUE] [float] NULL,
	[TRANSACTION_DATE] [datetime] NULL,
	[STATUS] [varchar](40) NULL,
	[SEFAZ_TYPE_INTEGRATION] [varchar](10) NULL,
	[SEFAZ_PAYMENT_INDICATOR] [varchar](10) NULL,
	[SEFAZ_NAME_PAYMENT] [varchar](30) NULL,
	[SEFAZ_NAME_CARD_ISSUER] [varchar](30) NULL,
	[SEFAZ_ID_PAYMENT] [varchar](10) NULL,
	[SEFAZ_ID_CARD_ISSUER] [varchar](10) NULL,
	[PARCELS] [int] NULL,
	[METHOD] [varchar](30) NULL,
	[DESCRIPTION] [varchar](60) NULL,
	[CARD_ISSUER] [varchar](40) NOT NULL,
	[AUTORIZATION_ID] [varchar](40) NOT NULL,
 CONSTRAINT [PK_SH_PAYMENT] PRIMARY KEY CLUSTERED 
(
	[CARD_ISSUER] ASC,
	[AUTORIZATION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

