CREATE TABLE [dbo].[SH_ATRIBUTOS](
	[NAME_KEY] [varchar](60) NOT NULL,
	[LABEL] [varchar](80) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[NAME_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

