CREATE VIEW [dbo].[V_TR_CATEGORIAS_FILHO] AS
	SELECT distinct (SELECT VALOR FROM CONFIGURACAO WHERE PARAMETRO = 31601) AS IDG2, TPF.TIPOPROD, TPF.TIPOPROD_FILHO, TPF.DESCRICAO, 
			('2' + CAST((SELECT VALOR FROM CONFIGURACAO WHERE PARAMETRO = 31601) AS VARCHAR(5)) 
			+ CAST(TPF.TIPOPROD_FILHO AS VARCHAR(5))) AS TIPOPROD_TRAY,
			LOWER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE( REPLACE(RTRIM(LTRIM(TPF.DESCRICAO)), '&', '-'), ' ', '-'), '/', '-'), '---', '--'), '--', '-'), '(', ''), ')', ''), '.', ''), ',', '')) collate SQL_Latin1_General_Cp1251_CS_AS as slug
		FROM TIPOPRODUTO_FILHO TPF, V_TR_CATEGORIAS_PAI TPP
		WHERE TPF.TIPOPROD = TPP.TIPOPROD
			AND TPF.DESCRICAO IS NOT NULL 
			AND TPF.DESCRICAO NOT LIKE ''
