CREATE  VIEW [dbo].[V_TR_PRODUTOS_INDISPONIBILIZAR] AS
	SELECT (SELECT VALOR FROM CONFIGURACAO WHERE PARAMETRO = 31601) AS IDG2, P.ID, P.EAN, P.PROD_NAME, isnull(A.QTMINIMA,1) AS QTMINIMA, A.QUANTIDADE STOCK,
		CASE WHEN (P.PROD_WEIGHT IS NULL OR P.PROD_WEIGHT = 0) THEN 100
		ELSE CEILING(P.PROD_WEIGHT * 100)
		END AS PROD_WEIGHT,
		CASE WHEN (P.PROD_LENGTH IS NULL OR P.PROD_LENGTH = 0) THEN 100
		ELSE CEILING(P.PROD_LENGTH * 100)
		END AS PROD_LENGTH,
		CASE WHEN (P.PROD_WIDTH IS NULL OR P.PROD_WIDTH = 0) THEN 100
		ELSE CEILING(P.PROD_WIDTH * 100)
		END AS PROD_WIDTH,
		CASE WHEN (P.PROD_HEIGHT IS NULL OR P.PROD_HEIGHT = 0) THEN 100
		ELSE CEILING(P.PROD_HEIGHT * 100)
		END AS PROD_HEIGHT
	FROM [V_TR_PRODUTOS] AS P, REGISTROS_SINCRONIZAR R,
		 ALMOXLOJAITENS AS A , V_PRODESTOQUE_CONSULTA as B
    WHERE	P.ID = R.PRODUTOID
			AND P.ID = A.PRODUTOID
			AND A.ALMOXID = ?
			AND A.ENTIDADEID_LOJA = ?
			AND P.ID = B.PRODUTOID
			AND A.ENTIDADEID_LOJA = B.ENTIDADEID_LOJA
			AND A.ALMOXID = B.ALMOXID
			AND isnull(A.QTMINIMA, 0) >= B.QTESTOQUE
		  AND R.DATAENTRADA >= (SELECT DATA_ULTIMA_SINCRONIZACAO FROM INTEGRACAO_ECOMMERCE WHERE INTEGRACAOID = 30)
	GROUP BY P.ID, P.PROD_NAME, P.EAN, A.QTMINIMA, B.QTESTOQUE, P.PROD_WEIGHT, P.PROD_LENGTH, P.PROD_WIDTH, P.PROD_HEIGHT,A.QUANTIDADE
