CREATE VIEW V_VTEX_SKUS_PRECOS AS
	SELECT DISTINCT (SELECT VALOR FROM CONFIGURACAO WHERE PARAMETRO = 31601) AS IDG2,
		P.PRODUTOID SKU_ID,
		P.PRODUTOID,
		descricao NOME,
		'TAB'+TPI.TABPRECOID IDENTIFICADOR_TABPRECO_API,
		TPI.PRECOCOMPRA,
		TPI.PRECOVENDA
	FROM PRODUTOS P JOIN INTEGRACAO_ECOMMERCE_PRODUTOS IEP ON (P.PRODUTOID = IEP.PRODUTOID)
	JOIN TABPRECOITEM TPI ON (IEP.PRODUTOID = TPI.PRODUTOID AND TPI.TABPRECOID IN (?) AND TPI.PRECOCOMPRA > 0 AND TPI.PRECOVENDA > 0)