CREATE VIEW V_VTEX_ALMOXARIFADOS AS
	SELECT DISTINCT (SELECT VALOR FROM CONFIGURACAO WHERE PARAMETRO = 31601) AS IDG2,
		ALI.ALMOXID,
		ALI.ENTIDADEID_LOJA,
		AL.DESCRICAO,
		-- A: ALMOX | L: LOJA
		'A'+ CAST(ALI.ALMOXID AS VARCHAR(10))+'L'+CAST(ALI.ENTIDADEID_LOJA AS VARCHAR(10)) IDENTIFICADOR_ALMOX_API
	FROM ALMOXLOJAITENS ALI JOIN ALMOXLOJA AL
	ON (ALI.ALMOXID  = AL.ALMOXID AND ALI.ENTIDADEID_LOJA = AL.ENTIDADEID_LOJA AND ALI.ALMOXID = ? AND ALI.ENTIDADEID_LOJA = ?)