CREATE VIEW [dbo].[V_VTEX_CATEGORIAS_PAI] AS
	SELECT distinct (SELECT VALOR FROM CONFIGURACAO WHERE PARAMETRO = 31601) AS IDG2, 
	TP.TIPOPROD,
	NULL TIPOPROD_FILHO,
	NULL TIPOPROD_NETO,
	NULL VTEXID_PAI,
	('1' + CAST((SELECT VALOR FROM CONFIGURACAO WHERE PARAMETRO = 31601) AS VARCHAR(5)) + CAST(TP.TIPOPROD AS VARCHAR(5))) AS TIPOPROD_VTEX,
	REPLACE(TP.DESCRICAO, '_', ' ') NAME, 
	REPLACE(TP.DESCRICAO, '_', ' ') TITLE, 
	'' DESCRIPTION,
	1 ISACTIVE
	FROM TIPOPRODUTO TP, PRODUTOS P , INTEGRACAO_ECOMMERCE_PRODUTOS IEP
	WHERE TP.TIPOPROD = P.TIPOPROD
		AND P.PRODUTOID = IEP.PRODUTOID
		AND TP.DESCRICAO IS NOT NULL 
		AND TP.DESCRICAO NOT LIKE ''