CREATE VIEW [dbo].[V_VTEX_CATEGORIAS_FILHO] AS
	SELECT distinct (SELECT VALOR FROM CONFIGURACAO WHERE PARAMETRO = 31601) AS IDG2,
	TPF.TIPOPROD,
	TPF.TIPOPROD_FILHO,
	NULL TIPOPROD_NETO,
	TPP.TIPOPROD_VTEX VTEXID_PAI,
	('2' + CAST((SELECT VALOR FROM CONFIGURACAO WHERE PARAMETRO = 31601) AS VARCHAR(5)) + CAST(TPF.TIPOPROD_FILHO AS VARCHAR(5))) AS TIPOPROD_VTEX,
	REPLACE(TPF.DESCRICAO, '_', ' ') NAME, 
	REPLACE(TPF.DESCRICAO, '_', ' ') TITLE, 
	'' DESCRIPTION,
	1 ISACTIVE
	FROM TIPOPRODUTO_FILHO TPF, [V_VTEX_CATEGORIAS_PAI] TPP, PRODUTOS P, INTEGRACAO_ECOMMERCE_PRODUTOS IEP
	WHERE TPF.TIPOPROD = TPP.TIPOPROD
		  AND TPF.DESCRICAO IS NOT NULL 
		  AND TPF.DESCRICAO NOT LIKE ''
		  AND TPF.TIPOPROD = P.TIPOPROD
		  AND TPF.TIPOPROD_FILHO = P.TIPOPRODID_FILHO
		  AND P.PRODUTOID = IEP.PRODUTOID