CREATE VIEW [dbo].[V_VTEX_CATEGORIAS_NETO] AS
	SELECT distinct (SELECT VALOR FROM CONFIGURACAO WHERE PARAMETRO = 31601) AS IDG2,
	TPN.TIPOPROD,
	TPN.TIPOPROD_FILHO,
	TPN.TIPOPROD_NETO,
	TPF.TIPOPROD_VTEX VTEXID_PAI,
	('3' + CAST((SELECT VALOR FROM CONFIGURACAO WHERE PARAMETRO = 31601) AS VARCHAR(5)) + CAST(TPN.TIPOPROD_NETO AS VARCHAR(5))) AS TIPOPROD_VTEX,
	REPLACE(TPN.DESCRICAO, '_', ' ') NAME, 
	REPLACE(TPN.DESCRICAO, '_', ' ') TITLE, 
	'' DESCRIPTION,
	1 ISACTIVE
	FROM TIPOPRODUTO_NETO TPN, V_VTEX_CATEGORIAS_FILHO TPF, PRODUTOS P, INTEGRACAO_ECOMMERCE_PRODUTOS IEP
	WHERE TPN.tipoprod_filho = TPF.tipoprod_filho
		AND TPN.TIPOPROD = TPF.tipoprod
		AND TPN.DESCRICAO IS NOT NULL 
		AND TPN.DESCRICAO NOT LIKE ''
		AND TPN.TIPOPROD = P.TIPOPROD
		AND TPN.TIPOPROD_FILHO = P.TIPOPRODID_FILHO
		AND TPN.TIPOPROD_NETO = P.TIPOPROD_NETO
		AND P.PRODUTOID = IEP.PRODUTOID