CREATE VIEW V_VTEX_PRODUTOS AS
	SELECT (SELECT VALOR FROM CONFIGURACAO WHERE PARAMETRO = 31601) AS IDG2,
		PRODUTOID,
		codigoCliente EAN,
		('1' + CAST((SELECT VALOR FROM CONFIGURACAO WHERE PARAMETRO = 31601) AS VARCHAR(5)) + CAST(ENTIDADEID_FORNECEDOR AS VARCHAR(10))) AS MARCAID_VTEX,
		CASE WHEN (P.TIPOPROD > 0 AND P.TIPOPRODID_FILHO > 0 AND P.TIPOPROD_NETO > 0) THEN TPN.TIPOPROD_VTEX
			WHEN (P.TIPOPROD > 0 AND P.TIPOPRODID_FILHO > 0 AND (P.TIPOPROD_NETO <= 0 OR P.TIPOPROD_NETO IS NULL)) THEN TPF.TIPOPROD_VTEX
			WHEN (P.TIPOPROD > 0 AND (P.TIPOPRODID_FILHO = 0 OR P.TIPOPRODID_FILHO IS NULL) AND (P.TIPOPROD_NETO = 0 OR P.TIPOPROD_NETO IS NULL)) THEN TP.TIPOPROD_VTEX
		END AS CATEGORIAID_VTEX,
		DESCRICAO_ECOMMERCE TITULO,
		DESCRICAO_ECOMMERCE NOME,
		ISNULL(CARACTERISTICA2, '') DESCRICAO,
		ISNULL(CARACTERISTICA2, '') DESCRICAO_PEQUENA,
		'1' ISACTIVE,
		'1' ISVISIBLE,
		'1' SHOW_WITHOUT_STOCK,
		PRODCOL.DESCRICAO PROD_COLECAO_FILTRO,
		PRODCAT.DESCRICAO PROD_CATEGORIA_FILTRO,
		PRODSTA.DESCRICAO PROD_STATUS_FILTRO,
		PRODGRU.DESCRICAO PROD_GRUPO_FILTRO
	FROM PRODUTOS P
		LEFT JOIN V_VTEX_CATEGORIAS_PAI TP ON P.TIPOPROD = TP.TIPOPROD
		LEFT JOIN V_VTEX_CATEGORIAS_FILHO TPF ON (P.TIPOPRODID_FILHO = TPF.TIPOPROD_FILHO AND P.TIPOPROD = TPF.TIPOPROD)
		LEFT JOIN V_VTEX_CATEGORIAS_NETO TPN ON (P.TIPOPROD_NETO = TPN.TIPOPROD_NETO AND P.TIPOPROD = TPN.TIPOPROD AND TPF.TIPOPROD_FILHO = TPN.TIPOPROD_FILHO)
		LEFT JOIN PRODUTOS_COLECOES PRODCOL ON (P.COLECAOID = PRODCOL.COLECAOID)
		LEFT JOIN PRODUTOS_CATEGORIA PRODCAT ON (P.CATEGORIAID = PRODCAT.CATEGORIAID)
		LEFT JOIN PRODUTO_STATUS PRODSTA ON (P.STATUSID = PRODSTA.STATUSID)
		LEFT JOIN PRODUTOS_GRUPOS PRODGRU ON (P.GRUPOID = PRODGRU.GRUPOID)
	WHERE PRODUTOID IN (SELECT PRODUTOID FROM INTEGRACAO_ECOMMERCE_PRODUTOS)
	AND DESCRICAO_ECOMMERCE IS NOT NULL
	AND DESCRICAO_ECOMMERCE <> ''