CREATE VIEW V_VTEX_SKUS_IMAGENS AS
	SELECT (SELECT VALOR FROM CONFIGURACAO WHERE PARAMETRO = 31601) AS IDG2,
	ID,
	PIMG.PRODUTOID,
	pimg.descricao LABEL,
	CAST(PIMG.PRODUTOID AS VARCHAR(30)) + CAST(ID AS VARCHAR(30)) NAME, -- Identificador da imagem na API
	1 IS_MAIN,
	PATH,
	IMGID_VTEX
	FROM PRODUTOS_IMAGENS PIMG 
	JOIN V_VTEX_PRODUTOS VTEXPROD
	ON (PIMG.PRODUTOID = VTEXPROD.PRODUTOID)