CREATE VIEW V_VTEX_ALMOX_ITENS AS
	SELECT DISTINCT (SELECT VALOR FROM CONFIGURACAO WHERE PARAMETRO = 31601) AS IDG2,
		P.PRODUTOID SKU_ID,
		P.PRODUTOID,
		ALI.ALMOXID,
		AL.DESCRICAO,
		ALI.QUANTIDADE,
		AL.IDENTIFICADOR_ALMOX_API
	FROM PRODUTOS P JOIN INTEGRACAO_ECOMMERCE_PRODUTOS IEP ON (P.PRODUTOID = IEP.PRODUTOID)
	JOIN ALMOXLOJAITENS ALI ON (P.PRODUTOID = ALI.PRODUTOID)
	JOIN V_VTEX_ALMOXARIFADOS AL ON (ALI.ALMOXID = AL.ALMOXID AND ALI.ENTIDADEID_LOJA = AL.ENTIDADEID_LOJA)