CREATE VIEW [dbo].[V_SH_PEDIDOS_ATUALIZAR] AS
	SELECT CODE, STATUS_CODE, STATUS_TYPE, STATUS_LABEL, INVOICE_KEY, INVOICE_VOLUME_QTY, SHIPMENT_CODE, SHIPMENT_DELIVERED_CARRIER_DATE, SHIPMENT_TRACK_CODE,
		   SHIPMENT_TRACK_CARRIER, SHIPMENT_TRACK_METHOD, SHIPMENT_TRACK_URL, SHIPMENT_EXCEPTION_OBSERVATION, SHIPMENT_EXCEPTION_OCCURRENCE_DATE
	FROM SH_PEDIDO P, REGISTROS_SINCRONIZAR_SH R
	WHERE P.CODE = R.PEDIDOID_API
		  AND DATASINCRONIZACAO IS NULL

