CREATE VIEW [dbo].[v_SiteEntidades] AS
	SELECT distinct (SELECT VALOR FROM CONFIGURACAO WHERE PARAMETRO = 31601) AS IDG2, a.ENTIDADEID, a.TIPO, a.CODCLI, LTRIM(a.DESCRICAO) AS DESCRICAO, LTRIM(LEFT(a.DESCRICAO2, 35)) as DESCRICAO2, 
			 LEFT(a.BAIRRO, 19)as BAIRRO, LEFT(a.CIDADE, 19) as CIDADE, a.UF, a.TIPO_JF, a.TIPOENTIDADEID, 
			 a.ENTIDADEID_VENDEDOR, 
			 a.TABPRECOID, a.PROFID, LEFT(a.CARTEIRAID, 19) as CARTEIRAID, a.REGTRIBUTARIAID, a.cidade_id, a.uf_id, a.REGTRIBID_PIS_COFINS, a.PAISID, 
			 a.ISENTO_CGF, a.CARTEIRA_SUBID, a.ATIVIDADEID, a.pais, LEFT(a.CNPJ_CPF, 19) as CNPJ_CPF, a.ATIVO, a.LIMITECREDITO, D.LIMITEDISPONIVEL, A.indice_aproveitamento,
			 LEFT(a.ENDERECO, 35) as ENDERECO, LEFT(a.CEP, 19) as CEP, LEFT(a.NUMERO, 19) as NUMERO, a.COMPLEMENTO, a.COMPLEMENTO as referencia_complemento, LEFT(a.CONTATO, 35) as responsavel_contato, LEFT(a.EMAIL, 35) as EMAIL,
			 CAST(a.OBS as varchar(8000)) as OBS, '' IMG_BASE_64
	FROM     dbo.ENTIDADES AS a INNER JOIN
			 dbo.V_CLIENTES AS D ON a.ENTIDADEID = D.ENTIDADEID
	WHERE    a.TIPO = '1'
			 AND A.ATIVO = 'S'
			 AND A.DESCRICAO IS NOT NULL
			 AND A.DESCRICAO <> ''
	union
	SELECT distinct (SELECT VALOR FROM CONFIGURACAO WHERE PARAMETRO = 31601) AS IDG2, a.ENTIDADEID, a.TIPO, a.CODCLI, LTRIM(a.DESCRICAO) AS DESCRICAO, LTRIM(LEFT(a.DESCRICAO2, 35)) as DESCRICAO2, 
			 LEFT(a.BAIRRO, 19)as BAIRRO, LEFT(a.CIDADE, 19) as CIDADE, a.UF, a.TIPO_JF, a.TIPOENTIDADEID, 
			 sup.entidadeid as ENTIDADEID_VENDEDOR, 
			 a.TABPRECOID, a.PROFID, LEFT(a.CARTEIRAID, 19) as CARTEIRAID, a.REGTRIBUTARIAID, a.cidade_id, a.uf_id, a.REGTRIBID_PIS_COFINS, a.PAISID, 
			 a.ISENTO_CGF, a.CARTEIRA_SUBID, a.ATIVIDADEID, a.pais, LEFT(a.CNPJ_CPF, 19) as CNPJ_CPF, a.ATIVO, a.LIMITECREDITO, D.LIMITEDISPONIVEL, A.indice_aproveitamento,
			 LEFT(a.ENDERECO, 35) as ENDERECO, LEFT(a.CEP, 19) as CEP, LEFT(a.NUMERO, 19) as NUMERO, a.COMPLEMENTO, a.COMPLEMENTO as referencia_complemento, LEFT(a.CONTATO, 35) as responsavel_contato, LEFT(a.EMAIL, 35) as EMAIL,
			 CAST(a.OBS as varchar(8000)) as OBS, '' IMG_BASE_64
	FROM     dbo.ENTIDADES AS a INNER JOIN
			 dbo.V_CLIENTES AS D ON a.ENTIDADEID = D.ENTIDADEID Inner join
			 entidades vend on (a.entidadeid_Vendedor = vend.entidadeid) inner join
			 entidades sup on (vend.entidadeid_vendedor = sup.entidadeid)
	WHERE	 a.TIPO = '1'
			 AND A.ATIVO = 'S'
			 AND A.DESCRICAO IS NOT NULL
			 AND A.DESCRICAO <> ''
	union
	  SELECT TOP 1 (SELECT VALOR FROM CONFIGURACAO WHERE PARAMETRO = 31601) AS IDG2, a.ENTIDADEID, a.TIPO, a.CODCLI, LTRIM(a.DESCRICAO) AS DESCRICAO, LTRIM(LEFT(a.DESCRICAO2, 35)) as DESCRICAO2, 
			 LEFT(a.BAIRRO, 19)as BAIRRO, LEFT(a.CIDADE, 19) as CIDADE, a.UF, a.TIPO_JF, a.TIPOENTIDADEID, 
			 a.ENTIDADEID_VENDEDOR, 
			 a.TABPRECOID, a.PROFID, LEFT(a.CARTEIRAID, 19) as CARTEIRAID, a.REGTRIBUTARIAID, a.cidade_id, a.uf_id, a.REGTRIBID_PIS_COFINS, a.PAISID, 
			 a.ISENTO_CGF, a.CARTEIRA_SUBID, a.ATIVIDADEID, a.pais, LEFT(a.CNPJ_CPF, 19) as CNPJ_CPF, a.ATIVO, a.LIMITECREDITO, D.LIMITEDISPONIVEL, A.indice_aproveitamento,
			 LEFT(a.ENDERECO, 35) as ENDERECO, LEFT(a.CEP, 19) as CEP, LEFT(a.NUMERO, 19) as NUMERO, a.COMPLEMENTO, a.COMPLEMENTO as referencia_complemento, LEFT(a.CONTATO, 35) as responsavel_contato, LEFT(a.EMAIL, 35) as EMAIL,
			 CAST(a.OBS as varchar(8000)) as OBS,
			 IMG.IMG_BASE_64
	FROM     ENTIDADES AS a INNER JOIN V_CLIENTES AS D ON a.ENTIDADEID = D.ENTIDADEID
			 INNER JOIN [TABLET_ENTIDADES_IMAGENS] IMG ON IMG.ENTIDADEID = D.ENTIDADEID
	WHERE    a.TIPO = '0'
			 AND A.ATIVO = 'S'
			 AND A.DESCRICAO IS NOT NULL
			 AND A.DESCRICAO <> ''