CREATE VIEW [dbo].[v_SiteMovDiaOrdensServico] AS
	Select (SELECT VALOR FROM CONFIGURACAO WHERE PARAMETRO = 31601) idg2, 
					MD.NUMDOCUMENTO, MD.CONTA, MD.ENTIDADEID_LOJA, MD.ALMOXID,
					MD.DATAEMISSAO, ISNULL(MD.FORMAPAGID, 1) FORMAPAGID, ISNULL(MD.CONDICAOID,1) CONDICAOID, MD.STATUS, CAST(MD.OBS as varchar(400)) OBS, 
					MD.ENTIDADEID_CLIENTE, MD.ENTIDADEID_FUNC, ISNULL(MD.TABPRECOID, 1) TABPRECOID, MD.TIPO, 
					MD.DATASAIDA, MD.COMISSAO, MD.desconto, MD.valortotalprod, MD.valorfrete,
					MD.valortotalnota, MD.valdesconto, ISNULL(MD.status_separacao, '') status_separacao, MD.prazo, CAST(MD.DEFEITOS AS varchar(400)) DEFEITOS,
					ISNULL(CAST(MD.SERVICOEXECUTADO as varchar(400)), '') SERVICOEXECUTADO, 
					ISNULL(MD.NUMSERIE_EQPO, '') NUMSERIE_EQPO, ISNULL(MD.EQPO, '') EQPO, ISNULL(MD.DATA_COMPRA, MD.DATAEMISSAO) DATA_COMPRA,
					ISNULL(MD.NUMNOTA_COMPRA, '') NUMNOTA_COMPRA, ISNULL(MD.garantia, 'N') garantia, 
					CLI.DESCRICAO CLIENTEDESCRICAO
				FROM    Entidades CLI, MOVIMENTO_DIA MD
				WHERE   MD.ENTIDADEID_CLIENTE = CLI.ENTIDADEID
					AND MD.STATUS IN ('4', '1')
					AND MD.tipo = '4'