CREATE VIEW [dbo].[v_siteClienteTabPreco] as
SELECT (SELECT VALOR FROM CONFIGURACAO WHERE PARAMETRO = 31601) AS IDG2,
	D.TABPRECOID,
	C.ENTIDADEID
FROM ENTIDADES C, TABPRECO D
WHERE C.TIPO = '1'
	AND C.TABPRECOID = D.TABPRECOID
	AND D.TABPRECOID IS NOT NULL