~ -- Se NÃO utilizar V_SITE_TABPRECO_X_USUARIOS
CREATE View [dbo].[v_sitetabpreco] AS
SELECT (SELECT VALOR FROM CONFIGURACAO WHERE PARAMETRO = 31601) idg2,
		TABPRECOID,
		DESCRICAO,
		CONDICAOID
FROM TABPRECO

~ -- Se utilizar V_SITE_TABPRECO_X_USUARIOS
CREATE View [dbo].[v_sitetabpreco] AS
SELECT (SELECT VALOR FROM CONFIGURACAO WHERE PARAMETRO = 31601) idg2,
		TABPRECOID,
		DESCRICAO,
		CONDICAOID
FROM TABPRECO
where TABPRECOID IN (select tabprecoid from [V_SITE_TABPRECO_X_USUARIOS])
GO
