CREATE VIEW [dbo].[v_siteClienteFormaPagCondicao] as
	SELECT (SELECT VALOR FROM CONFIGURACAO WHERE PARAMETRO = 31601) AS IDG2,
             ENTIDADEID_CLIENTE,
             FORMAPAGID,
             CONDICAOID
	FROM CLIENTE_CONDICAO