CREATE VIEW [dbo].[v_SiteConsignacaoRotaVendedor] AS
	SELECT (SELECT VALOR FROM CONFIGURACAO WHERE PARAMETRO = 31601) AS IDG2, 
		A.ROTAID, A.DESCRICAO, A.ENTIDADEID_VENDEDOR, A.STATUS, A.TIPO, 
		A.TIPO_ROTA,  B.ENTIDADEID_CLIENTE, B.SEQUENCIA
	FROM rota_vendedor a, ROTA_VENDEDOR_CLIENTES b , V_VENDEDOR_CONSIGNADO C
	WHERE a.ROTAID = b.rotaid
		AND A.ENTIDADEID_VENDEDOR = C.ENTIDADEID
		AND UPPER(STATUS) = 'S'