CREATE VIEW [dbo].[v_SiteEquipesVendaConsignacao] as
	SELECT (SELECT VALOR FROM CONFIGURACAO WHERE PARAMETRO = 31601) IDG2, SUP.ENTIDADEID ENTIDADEID_EQUIPE, 
		SUP.DESCRICAO DESCRICAO_EQUIPE, VEND.ENTIDADEID ENTIDADEID_VENDEDOR, VEND.DESCRICAO DESCRICAO_VENDEDOR
	FROM ENTIDADES SUP JOIN ENTIDADES VEND ON (SUP.ENTIDADEID = VEND.ENTIDADEID_VENDEDOR)
	where sup.tipo = '3'
	and vend.tipo = '3'
