CREATE VIEW v_SitePedidosFaturados AS
	SELECT (SELECT VALOR FROM CONFIGURACAO WHERE PARAMETRO = 31601) AS IDG2,
		   CONTA,
		   ENTIDADEID_LOJA,
		   NUMDOCUMENTO AS NUMPEDIDO,
		   DATAEMISSAO,
		   ENTIDADEID_FUNC,
		   ENTIDADEID_CLIENTE,
		   VALORTOTALPROD AS TOTALPRODUTOS,
		   VALORTOTALNOTA AS TOTALNOTA,
		   VALORTOTALPROD - VALORTOTALNOTA AS DESCONTOS,
		   NUM_NOTA = ISNULL((SELECT TOP 1 NUMDOCUMENTO FROM MOVIMENTO_DIA	
							  WHERE TIPO = '8' AND STATUS = '3'
							  AND CONTAORIGEM = CONTA AND ENTIDADEID_LOJA_ORIGEM = ENTIDADEID_LOJA), '0'),
		  CONDICAOID, FORMAPAGID, PRAZO, SUBSTRING(OBS,1, 300) AS OBS	
	FROM MOVIMENTO_DIA
	WHERE TIPO = '1'
	AND STATUS = '2'
	and dataemissao >= DATEADD(day, -105, getdate()) -- Últimos 105 dias
	GROUP BY CONTA,
		   ENTIDADEID_LOJA,
		   NUMDOCUMENTO,
		   DATAEMISSAO,
		   ENTIDADEID_FUNC,
		   ENTIDADEID_CLIENTE,
		   VALORTOTALPROD,
		   VALORTOTALNOTA, CONDICAOID, FORMAPAGID, PRAZO, SUBSTRING(OBS,1, 300)