CREATE VIEW [dbo].[V_SITE_TIPO_VISITASEMPEDIDO] AS
	SELECT (SELECT VALOR FROM CONFIGURACAO WHERE PARAMETRO = 31601) as IDG2,
		 A.TIPOSERVID, A.descricao AS DESCRICAO
	FROM TIPOSERVICO A 
	WHERE TIPO  = 'F'