CREATE view [dbo].[V_SITE_CARGAS] AS
	SELECT distinct (SELECT VALOR FROM CONFIGURACAO WHERE PARAMETRO = 31601) AS IDG2, 
		A.cargaid, A.data, A.descricao AS DESCRICAO_CARGA, A.status, 
		A.ENTIDADEID_MOTORISTA, A.KM_INICIAL, A.KM_FINAL, A.veiculoid, 
		A.entidadeid_loja, CAST(A.obs AS VARCHAR(500)) as obs, A.entregue, A.entidadeid_transp,
		A.rotaid, A.data_saida, A.data_retorno, A.total_entrega,
		A.peso_max, A.TIPOSERVID, A.ENTIDADEID_ENTREGADOR1, 
		A.ENTIDADEID_ENTREGADOR2, 
		B.DESCRICAO as nome_Motorista,
		C.PLACA, C.DESCRICAO, C.ANTT
	FROM REGISTROS_SINCRONIZAR D, 
		 CARGA A INNER JOIN ENTIDADES B ON (A.ENTIDADEID_MOTORISTA = B.ENTIDADEID)
				 LEFT JOIN VEICULOS C  ON  (A.VEICULOID = C.VEICULOID)
	WHERE 
		A.CARGAID = D.CARGAID
		AND A.STATUS = 4 --> Status: Em rota
		AND D.DATASINCRONIZACAO IS NULL
		AND A.DATA >= DATEADD(DAY,-15, GETDATE()) -- Dos últimos 15 dias
		AND A.CARGAID IN (SELECT CARGAID FROM Carga_Romaneio_Ped)
		UNION
	SELECT distinct (SELECT VALOR FROM CONFIGURACAO WHERE PARAMETRO = 31601) AS IDG2, 
		A.cargaid, A.data, A.descricao AS DESCRICAO_CARGA, A.status, 
		A.ENTIDADEID_MOTORISTA, A.KM_INICIAL, A.KM_FINAL, A.veiculoid, 
		A.entidadeid_loja, CAST(A.obs AS VARCHAR(500)) as obs, A.entregue, A.entidadeid_transp,
		A.rotaid, A.data_saida, A.data_retorno, A.total_entrega,
		A.peso_max, A.TIPOSERVID, A.ENTIDADEID_ENTREGADOR1, 
		A.ENTIDADEID_ENTREGADOR2, 
		B.DESCRICAO as nome_Motorista,
		C.PLACA, C.DESCRICAO, C.ANTT
	FROM REGISTROS_SINCRONIZAR D, 
		 CARGA A INNER JOIN ENTIDADES B ON (A.ENTIDADEID_MOTORISTA = B.ENTIDADEID)
				 LEFT JOIN VEICULOS C  ON  (A.VEICULOID = C.VEICULOID)
	WHERE 
		A.CARGAID = D.CARGAID
		AND A.STATUS = 2 --> Status: Finalizado
		AND D.DATASINCRONIZACAO IS NULL
		AND A.DATA >= DATEADD(DAY,-7, GETDATE())  -- Dos últimos 7 dias
		AND A.CARGAID IN (SELECT CARGAID FROM Carga_Romaneio_Ped)
