CREATE view [dbo].[v_Site_CargasPedidos] AS
	SELECT (SELECT VALOR FROM CONFIGURACAO WHERE PARAMETRO = 31601) AS IDG2, A.cargaid, a.ROMANEIOID, a.entidadeid_loja, a.conta, a.ordem,
		B.NUMDOCUMENTO, 
		CASE WHEN(a.entregue IS NULL OR A.ENTREGUE = 'n' OR A.ENTREGUE = 'N') THEN 'N'
		ELSE 'S'
		END AS entregue, a.MOTIVONAOENTREGUE,  	
		B.ENTIDADEID_CLIENTE, 
		CLI.DESCRICAO as CLI_RAZAOSOCIAL, B.VALORTOTALNOTA as VALORTOTALNOTA,
		B.VALORFRETE as VALORFRETE,
		CLI.CEP, CLI.ENDERECO, CLI.NUMERO, CLI.COMPLEMENTO, CLI.BAIRRO, CLI.CIDADE, CLI.UF,
		B.DATAEMISSAO as DT_EMISSAO, A.LATITUDE AS latitude_checkin, A.LONGITUDE AS longitude_checkin, A.CIDADE AS cidade_checkin,
		A.ESTADO AS estado_checkin, A.CEP AS cep_checkin, A.RUA AS rua_checkin, 
		A.DATA_CHECKIN, A.DATA_ENTREGA, A.DATA_NAO_ENTREGUE, 
		A.OCORRENCIAID, A.DATA_CHECKIN_UPD, A.DATA_ENTREGA_UPD, A.DATA_NAO_ENTREGUE_UPD,
		isnull(B.Quantidade, 0) as Volumes, a.IMAGEM_RECIBO, A.JUSTIFICATIVAATRASO
	FROM v_Site_Cargas X, Carga_Romaneio_Ped A
		LEFT JOIN Movimento_Dia B on (isnull(A.ENTIDADEID_LOJA_PEDIDO,A.Entidadeid_Loja) = B.Entidadeid_Loja and A.Conta = B.Conta)
		LEFT JOIN V_Clientes CLI on (B.ENTIDADEID_CLIENTE = CLI.ENTIDADEID)
	WHERE X.CARGAID = A.CARGAID
