CREATE VIEW [dbo].[V_LI_MARCA] AS
	SELECT A.MARCAID AS id,
		A.descricao
	from MARCA A JOIN PRODUTOS B ON (A.MARCAID = B.MARCAID)
		  JOIN INTEGRACAO_ECOMMERCE_PRODUTOS C ON (C.PRODUTOID = B.PRODUTOID)
	GROUP BY A.MARCAID, A.descricao 