/*									Duas opções de view disponíveis:	
									[1]: Atualização de Produto utilizando AlmoxLojaItens
									[2]: Atualização de Produto utilizando TABPRECOITEM

									[ATENÇÃO]: Verificar se o cliente já possui uma dessas views aplicadas; Se houver, prestar atenção em qual regra o cliente utiliza
													para que não haja sobrescrita com uma view diferente. É necessário se atentar também aos campos marcados com "?",
													pois ele difere para cada cliente e regra. Então, se o cliente já tiver uma delas aplicada, olhar a regra antes
													de atualizar.
*/


-- [1]: Atualização de Produto utilizando AlmoxLojaItens
CREATE VIEW [dbo].[V_LI_PRODUTO_ATUALIZAR] AS
	SELECT P.DESCRICAO, P.ATIVO, P.ALTURA, P.LARGURA, P.PESO, P.COMPRIMENTO, P.PRODUTOID, P.CLAFISCAL as NCM, P.CODIGOCLIENTE AS GTIN, P.TIPOPROD AS CATEGORIA,
		I.PRODUTOID_API, 
		A.QUANTIDADE
	FROM PRODUTOS AS P, 
		INTEGRACAO_ECOMMERCE_PRODUTOS AS I,
		ALMOXLOJAITENS AS A,
		REGISTROS_SINCRONIZAR R
    WHERE I.PRODUTOID = P.PRODUTOID
		AND I.PRODUTOID = A.PRODUTOID
		AND I.PRODUTOID = R.PRODUTOID
		AND A.QUANTIDADE >= 1
		AND A.ALMOXID = ?
		AND A.ENTIDADEID_LOJA = ?
		AND PRODUTOID_API IS NOT NULL
		AND R.DATAENTRADA >= (SELECT DATA_ULTIMA_SINCRONIZACAO FROM INTEGRACAO_ECOMMERCE WHERE INTEGRACAOID = 1)
	GROUP BY P.DESCRICAO, P.ATIVO, P.ALTURA, P.LARGURA, P.PESO, P.COMPRIMENTO, P.PRODUTOID, P.CLAFISCAL, P.CODIGOCLIENTE,
			P.TIPOPROD, I.PRODUTOID_API, A.QUANTIDADE


-- [2]: Atualização de Produto utilizando TABPRECOITEM
CREATE VIEW [dbo].[V_LI_PRODUTO_ATUALIZAR] AS
	SELECT TPI.TABPRECOID, P.DESCRICAO, P.ATIVO, P.ALTURA, P.LARGURA, P.PESO, P.COMPRIMENTO, P.PRODUTOID, P.CLAFISCAL as NCM, P.CODIGOCLIENTE AS GTIN, P.TIPOPROD AS CATEGORIA,
		I.PRODUTOID_API, 
		A.QUANTIDADE
	FROM PRODUTOS AS P, 
		INTEGRACAO_ECOMMERCE_PRODUTOS AS I,
		ALMOXLOJAITENS AS A ,
		TABPRECOITEM AS TPI,
		REGISTROS_SINCRONIZAR R
    WHERE I.PRODUTOID = P.PRODUTOID
		AND I.PRODUTOID = A.PRODUTOID
		AND I.PRODUTOID = R.PRODUTOID
		AND TPI.PRODUTOID = I.PRODUTOID
		AND A.QUANTIDADE >= 1
		AND TPI.TABPRECOID = ?
		AND A.ALMOXID = ?
		AND A.ENTIDADEID_LOJA = ?
		AND PRODUTOID_API IS NOT NULL
		AND R.DATAENTRADA >= (SELECT DATA_ULTIMA_SINCRONIZACAO FROM INTEGRACAO_ECOMMERCE WHERE INTEGRACAOID = 1)
	GROUP BY TPI.TABPRECOID, P.DESCRICAO, P.ATIVO, P.ALTURA, P.LARGURA, P.PESO, P.COMPRIMENTO, P.PRODUTOID, P.CLAFISCAL,
			 P.CODIGOCLIENTE, P.TIPOPROD, I.PRODUTOID_API, A.QUANTIDADE
