CREATE VIEW [dbo].[V_LI_PRODUTOS_INDISPONIBILIZAR] AS
	SELECT  P.PRODUTOID, P.DESCRICAO, P.ATIVO, P.ALTURA, P.LARGURA, P.PESO, P.COMPRIMENTO, P.CLAFISCAL as NCM, P.CODIGOCLIENTE AS GTIN, P.TIPOPROD AS CATEGORIA,
	I.PRODUTOID_API, 0 AS QUANTIDADE
	FROM PRODUTOS AS P, INTEGRACAO_ECOMMERCE_PRODUTOS AS I, ALMOXLOJAITENS AS A , V_PRODESTOQUE_CONSULTA as B
    WHERE I.PRODUTOID = P.PRODUTOID
	AND I.PRODUTOID = A.PRODUTOID
	and a.entidadeid_loja = b.entidadeid_loja
	and a.almoxid = b.almoxid
	and a.produtoid = b.produtoid
	AND A.QTMINIMA > 0
	AND A.QTMINIMA >= b.qtestoque
	AND A.ALMOXID = 0
	AND A.ENTIDADEID_LOJA = 0
    AND PRODUTOID_API IS NOT NULL
GO

