CREATE VIEW [dbo].[V_LI_SEO] AS
SELECT A.PRODUTOID,
	A.DESCRICAO AS TITLE,
	ISNULL(A.CODIGOCLIENTE, ' ') + ' ' + ISNULL(A.APLICACAO1, ' ') + ' ' + ISNULL(A.APLICACAO2, ' ') AS keyword,
	substring(A.CARACTERISTICA2, 1, 400) as description
FROM PRODUTOS A JOIN INTEGRACAO_ECOMMERCE_PRODUTOS B ON (A.PRODUTOID = B.PRODUTOID)
GO

