CREATE TABLE TR_PAYMENT(
	ORDER_ID VARCHAR(10),
	PAYMENT_ID VARCHAR(10),
	PAYMENT_METHOD_ID VARCHAR(10),
	METHOD VARCHAR(100),
	PAYMENT_PLACE VARCHAR(100),
	VALUE VARCHAR(20),
	NOTE TEXT,
	AUTORIZACAO_ARP VARCHAR(20),
	NSU VARCHAR(20),
	CONSTRAINT PK_PAYMENT PRIMARY KEY (ORDER_ID, PAYMENT_ID)
)